Doc update for list class
CodemateLtd/sdk pull request #20
Opened 2021-11-05 13:15 UTC by jpsiitonen

Updating example code blocks for core:List class and landing page

2021-11-09 13:14 UTC, alexlindroos commented on sdk/lib/core/list.dart
> +/// final growableList = []; // []
Maybe add print `(growableList);` // [] instead

2021-11-10 06:25 UTC, jpsiitonen commented on sdk/lib/core/list.dart
> +/// final growableList = []; // []
done.

2021-11-16 09:05 UTC, alexlindroos requested changes

2021-11-16 09:05 UTC, alexlindroos commented on sdk/lib/core/list.dart
> +  /// print(parts); // [head, shoulder, toes]
[head, shoulder, knees] is the right print

2021-11-16 09:05 UTC, alexlindroos commented on sdk/lib/core/list.dart
> +  /// print(colors.sublist(3)); // [green, blue, orange, pink]
Should the print be `[orange, pink]`

2021-11-16 09:05 UTC, alexlindroos commented on sdk/lib/core/list.dart
> +/// // Check is value 'E' on list otherwise return 'N'
nit: add line breaks to this chunk of code to make it more readable

2021-11-16 09:17 UTC, jpsiitonen commented on sdk/lib/core/list.dart
> +  /// print(colors.sublist(3)); // [green, blue, orange, pink]
yes

2021-11-16 09:32 UTC, alexlindroos approved these changes

2021-11-17 21:46 UTC, stepthomp approved these changes

2021-11-26 07:30 UTC, closed without merging