Doc update core:map class
CodemateLtd/sdk pull request #21
Opened 2021-11-09 07:47 UTC by jpsiitonen

Updating example codes for map methods usage.

2021-11-10 14:59 UTC, tomgilder requested changes

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// final data = {1: 'A', 2: 'B', 3: 'C'};
I think we should use something other than 123/ABC - let's discuss

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// print(mapOf.runtimeType); // LinkedHashMap
With all of these examples the `runtimeType` has generic params 

So this prints `LinkedHashMap<int, String>` - I think we should be accurate with that?

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// final words = ['bad', 'cat'];
why is the cat bad 😢

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// final isA = data.containsValue('A'); // false
```suggestion
  /// final containsA = data.containsValue('A'); // false
```

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// final isZ = data.containsValue('Z'); // true
```suggestion
  /// final containsZ = data.containsValue('Z'); // true
```

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// final isA = data.containsKey('A'); // true
```suggestion
  /// final containsA = data.containsKey('A'); // true
```

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// final isZ = data.containsKey('Z'); // false
```suggestion
  /// final containsZ = data.containsKey('Z'); // false
```

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// print(map1); // {A: X, B: Y, C: Z, E: AB, F: CD}
I just can't follow these letters easily, needs to be something else easier to follow

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// print(customMap);
I don't think we need these examples of using the standard Map syntax

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
>    V update(K key, V update(V value), {V ifAbsent()?});
This example needs work, and I think the text does too - me and Alex both weren't clear on what this method does.

- The text doesn't explain what `ifAbsent` actually does
- What happens if they key doesn't exist and you don't provide `ifAbsent`?
- It also doesn't explain what `value` is - I'm assuming it's the current value of that key? There could be an example of using the current value to update the map

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// ```
I suggest adding a couple of line breaks just to split this up
```
   /// ```dart
   /// final data = {1: 'A', 2: 'B', 3: 'C'};
   /// 
   /// data.updateAll((key, value) => 'AB');
   /// print(data); // {1: AB, 2: AB, 3: AB}
   /// 
   /// data.updateAll((key, value) => key.toString());
   /// print(data); // {1: 1, 2: 2, 3: 3}
   /// ```
```

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// // Return value is current value and no update done if key exists on map
```suggestion
  /// // If the key already exists, the current value is returned, and the Map isn't modified.
```

2021-11-10 14:59 UTC, tomgilder commented on sdk/lib/core/map.dart
> +  /// // Return value is current value and no update done if key exists on map
Also wondering if this should be a separate example - or if not, at least separate with a new line

2021-11-16 09:00 UTC, alexlindroos approved these changes

2021-11-18 10:07 UTC, stepthomp approved these changes

2021-11-26 07:33 UTC, closed without merging