Doc update core:set
CodemateLtd/sdk pull request #22
Opened 2021-11-09 07:54 UTC by jpsiitonen

Added example codes to methods which are defined in set. 
Currently there are no updates for Core:Set landing page ( already documented properly )

2021-11-10 14:17 UTC, tomgilder requested changes

2021-11-10 14:17 UTC, tomgilder commented on sdk/lib/core/set.dart
> +  /// final isB = characters.contains('B'); // true
nit

```suggestion
  /// final containsB = characters.contains('B'); // true
```

2021-11-10 14:17 UTC, tomgilder commented on sdk/lib/core/set.dart
> +  /// final isD = characters.contains('D'); // false
```suggestion
  /// final containsD = characters.contains('D'); // false
```

2021-11-10 14:17 UTC, tomgilder commented on sdk/lib/core/set.dart
> +  /// final removeB = characters.remove('B'); // true
```suggestion
  /// final didRemoveB = characters.remove('B'); // true
```

2021-11-10 14:17 UTC, tomgilder commented on sdk/lib/core/set.dart
> +  /// final removeD = characters.remove('D'); // false
```suggestion
  /// final didRemoveD = characters.remove('D'); // false
```

2021-11-10 14:17 UTC, tomgilder commented on sdk/lib/core/set.dart
> +  /// final isB = characters.lookup('B');
```suggestion
  /// final b = characters.lookup('B');
```

2021-11-10 14:17 UTC, tomgilder commented on sdk/lib/core/set.dart
> +  /// print(isB); // B
```suggestion
  /// print(b); // B
```

2021-11-16 08:54 UTC, alexlindroos approved these changes

2021-11-18 11:19 UTC, stepthomp approved these changes

2021-11-26 07:35 UTC, closed without merging