Doc update core:DateTime
CodemateLtd/sdk pull request #28
Opened 2021-11-23 14:52 UTC by jpsiitonen

2021-11-24 11:39 UTC, alexlindroos commented on sdk/lib/core/date_time.dart
> +/// final localDay = dDay.toLocal(); // fx 1944-06-06 02:00:00.000
fx?

2021-11-24 11:45 UTC, alexlindroos commented on sdk/lib/core/date_time.dart
> +/// final difference = berlinWallFell.difference(moonLanding);
should we add comment or print here?

2021-11-24 11:46 UTC, alexlindroos commented on sdk/lib/core/date_time.dart
> +  /// final thisInstant = DateTime.now();
Why not use the same variable name than before "now" ?

2021-11-24 11:48 UTC, alexlindroos requested changes

2021-11-24 11:48 UTC, alexlindroos commented on sdk/lib/core/date_time.dart
> +  /// final difference = berlinWallFell.difference(dDay);
should we add comment or print of `difference`?

2021-11-24 13:03 UTC, jpsiitonen commented on sdk/lib/core/date_time.dart
> +/// final difference = berlinWallFell.difference(moonLanding);
sure.

2021-11-24 13:57 UTC, jpsiitonen commented on sdk/lib/core/date_time.dart
> +/// final localDay = dDay.toLocal(); // fx 1944-06-06 02:00:00.000
may be e.g is better..

2021-11-26 14:00 UTC, alexlindroos approved these changes

2021-11-29 13:05 UTC, stepthomp approved these changes

2021-11-30 09:07 UTC, closed without merging