Doc update for HashMap
CodemateLtd/sdk pull request #8
Opened 2021-10-21 11:02 UTC by jpsiitonen

Doc update for HashMap

2021-10-26 05:30 UTC, alexlindroos commented on sdk/lib/collection/hash_map.dart
> +/// final HashMap<int, String> anotherHasMap = HashMap();
typo there, should be anotherHashMap

2021-10-26 05:48 UTC, alexlindroos commented on sdk/lib/collection/hash_map.dart
> +/// final cExists =  hashMap.containsValue('c'); // false
This works, but maybe even more clearer example is to change c to a letter which is not in A,B,C,D

2021-10-26 05:50 UTC, jpsiitonen commented on sdk/lib/collection/hash_map.dart
> +/// final cExists =  hashMap.containsValue('c'); // false
Yep. That's true. 👍  Used same example character also on other PRs so need to update them also.

2021-10-26 06:04 UTC, alexlindroos commented on sdk/lib/collection/hash_map.dart
> +/// ```dart
Do we need prints for the output?

2021-10-26 06:31 UTC, alexlindroos commented on sdk/lib/collection/hash_map.dart
> +/// hashMap.removeWhere((key, value) => key == 2);
You are removing the same element with` key == 2` and `value == "B"` 

In LinkedHashMap there is removed two different elements, is this on purpose?

2021-10-26 06:33 UTC, jpsiitonen commented on sdk/lib/collection/hash_map.dart
> +/// ```dart
I don't think it provides more value, because these are constructor options..

2021-10-26 06:34 UTC, jpsiitonen commented on sdk/lib/collection/hash_map.dart
> +/// hashMap.removeWhere((key, value) => key == 2);
Ah. No, that was not purpose. Need to use similar code behaviour with other examples too..

2021-11-01 09:18 UTC, alexlindroos approved these changes

2021-11-09 10:35 UTC, tomgilder commented
**General feedback about the documentation**

> A hash-table based implementation of [Map].

I don't know what this means.

Questions I have about this class:

- Why and when would I use this instead of a `Map`?
- Is this the default implementation for a `Map`?
  - Answer: no, it isn't - `LinkedHashMap` is - but that's not clearly stated even in `Map` docs
- If not, how is it different?
- What other `Map` implementations are there? How do I compare them?
  - Feels like the `Map` doc page should help me choose between them better

2021-11-09 10:59 UTC, jpsiitonen commented
Actually the **Map** class page is trying to answer some of the questions. https://api.dart.dev/stable/2.14.4/dart-core/Map-class.html

2021-11-10 14:00 UTC, tomgilder commented on sdk/lib/collection/hash_map.dart
> +/// throws an exception: [ConcurrentModificationError].
I don't think "manipulating item count" is quite clear enough here.

There's quite a nice paragraph from the `Map` documentation, it might be better just copying that?...

> It is generally not allowed to modify the map (add or remove keys) while an operation is being performed on the map, for example in functions called during a forEach or putIfAbsent call. Modifying the map while iterating the keys or values may also break the iteration.

2021-11-10 14:00 UTC, tomgilder commented on sdk/lib/collection/hash_map.dart
> +/// throws an exception: [ConcurrentModificationError].
Also not sure if specifying the error is actually useful? But I can debate with myself 😁

Like, the message needs to be "don't do this" - it's not an error you'd ever want to catch

2021-11-10 14:00 UTC, tomgilder commented on sdk/lib/collection/hash_map.dart
> +/// // To check is the map empty, use isEmpty or isNotEmpty
```suggestion
/// // To check if the map is empty, use isEmpty or isNotEmpty
```

2021-11-11 10:27 UTC, jpsiitonen commented on sdk/lib/collection/hash_map.dart
> +/// throws an exception: [ConcurrentModificationError].
that's good idea.

2021-11-12 13:05 UTC, alexlindroos commented on sdk/lib/collection/hash_map.dart
> +/// The [HashMap] is unordered (the order of iteration is not guaranteed).
I don't really feel having the explanation of unordered inside brackets. I would rather have it inside the sentence somehow. What @stepthomp thinks?

2021-11-12 13:16 UTC, alexlindroos requested changes

2021-11-12 13:16 UTC, alexlindroos commented on sdk/lib/collection/hash_map.dart
> +  /// print(hashMap.runtimeType);
This line can be removed, right?

2021-11-17 07:46 UTC, stepthomp approved these changes

2021-11-17 08:23 UTC, closed without merging